### ISSUE TITLE
line number ack format not being parsed

### ISSUE THREAD

**Issue by hemna** [rossengeorgiev/aprs-python#58]
According to the spec here: 
http://www.aprs.org/aprs11/replyacks.txt

Message id line number with acks should be parsed out, but don't seem to be.

```
└─[$] <> cat test-2.py
import aprslib
import pprint
msg = "KO4KWC-6>APRS,TCPIP*,qAC,T2MCI::KO4KWC-14:weather ve3kbr {22}AA"
packet = aprslib.parse(msg)
pprint.pprint(packet)
```

Results in

```
└─[$] <> python test-2.py
{'addresse': 'KO4KWC-14',
 'format': 'message',
 'from': 'KO4KWC-6',
 'message_text': 'weather ve3kbr {22}AA',
 'path': ['TCPIP*', 'qAC', 'T2MCI'],
 'raw': 'KO4KWC-6>APRS,TCPIP*,qAC,T2MCI::KO4KWC-14:weather ve3kbr {22}AA',
 'to': 'APRS',
 'via': 'T2MCI'}
```

**Comment by joergschultzelutter** [comment]
FWIW, I have a [pending pull request](https://github.com/rossengeorgiev/aprs-python/pull/61) which should enable the parser to recognize this 'more recent' format. At the moment, my APRS daemon (which uses Rossen's library) depends on a native post-processing approach in order to parse both old and new formats; this PR should eliminate that need.
